export interface Env {
  ROOT_URL: string;
  PROCESS_SLACK_MESSAGES_QUEUE_BINDING: Queue<any>;
  UPLOAD_FILES_TO_ZENDESK_QUEUE_BINDING: Queue<any>;
  SLACK_CONNECTION_CREATED_QUEUE_BINDING: Queue<any>;
  STRIPE_SUBSCRIPTION_CHANGED_QUEUE_BINDING: Queue<any>;
  SLACK_APP_UNINSTALLED_QUEUE_BINDING: Queue<any>;
  SLACK_CLIENT_SECRET: string;
  SLACK_CLIENT_ID: string;
  SLACK_SIGNING_SECRET: string;
  ENCRYPTION_KEY: string;
  STRIPE_API_KEY: string;
  DEFAULT_STRIPE_PRODUCT_ID: string;
  STRIPE_ENDPOINT_SECRET: string;
  SUBSCRIPTION_EXPIRATION_BUFFER_HOURS: number;
  POSTHOG_ANALYTICS_KEY: string;
  INTERNAL_SLACKBOT_ACCESS_TOKEN: string;
  ZENDESK_OAUTH_SECRET: string;
  SLACK_OAUTH_STATE: string;
  HYPERDRIVE: Hyperdrive;
}
