export interface Env {
  BETTER_STACK_SOURCE_TOKEN: string;
  ROOT_URL: string;
  PROCESS_SLACK_MESSAGES_QUEUE_BINDING: Queue<any>;
  UPLOAD_FILES_TO_ZENDESK_QUEUE_BINDING: Queue<any>;
  SLACK_SIGNING_SECRET: string;
  ENCRYPTION_KEY: string;
}
